### ISSUE TITLE
UI shows timestamps different than CLI

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2web#160] opened 2015-06-17 17:54 UTC
CLI uses UTC. We should be consistent with CLI but in UI allow timestamps to be displayed in local time by clicking some button. 

reported by: @skarmark on IRC

**Comment by Kami** [comment] 2015-06-17 18:00
Agreed. Should default to UTC everywhere, optionally allowing user to select a local time zone (not a big priority right now).

**Comment by enykeev** [comment] 2015-06-18 12:48
I'm sorry, but I'm unable to reproduce the original problem. As far as I can tell, timestamp representation is consistent between UI and CLI.

```
enykeev@st2stage201:~$ st2 run core.local "date -u"
.
id: 5582ba96ce36d21702e3a4e4
status: succeeded
result:
{
    "failed": false,
    "stderr": "",
    "return_code": 0,
    "succeeded": true,
    "stdout": "Thu Jun 18 12:33:26 UTC 2015
"
}
```

The second execution, `5582bae2ce36d21702e3a4e6`, was created a minute later in UI. The history records of both executions are:

```
enykeev@st2stage201:~$ st2 execution list -n 2
+--------------------------+------------+--------------+-----------+---------------------------+---------------------------+
| id                       | action.ref | context.user | status    | start_timestamp           | end_timestamp             |
+--------------------------+------------+--------------+-----------+---------------------------+---------------------------+
| 5582ba96ce36d21702e3a4e4 | core.local | testu        | succeeded | Thu, 18 Jun 2015 12:33:26 | Thu, 18 Jun 2015 12:33:26 |
|                          |            |              |           | UTC                       | UTC                       |
| 5582bae2ce36d21702e3a4e6 | core.local | testu        | succeeded | Thu, 18 Jun 2015 12:34:42 | Thu, 18 Jun 2015 12:34:42 |
|                          |            |              |           | UTC                       | UTC                       |
+--------------------------+------------+--------------+-----------+---------------------------+---------------------------+
```

![2015-06-18 18 43 30](https://cloud.githubusercontent.com/assets/1357357/8231390/a0400028-15e1-11e5-8579-65418fe2b54a.png)

**Comment by enykeev** [comment] 2015-06-18 12:55
As for default TZ to show, I would suggest instead make both UI and CLI to show timestamps in local TZ with an ability to switch to UTC on request. It just seem more natural to me.

**Comment by Kami** [comment] 2015-06-18 12:56
@enykeev This might be more natural, but I think it's actually better if it defaults to UTC so by default, everyone sees the same outputs.

That's important if you for debugging / troubleshooting and if you share output with someone. It results in less surprises.

**Comment by dzimine** [comment] 2015-08-26 04:50
@Kami can you please validate that it's no longer issue?

**Comment by Kami** [comment] 2015-08-26 13:20
I checked and verified that UI now correctly displays timestamps in UTC.

**Comment by estee-tew** [comment] 2016-09-16 19:38
https://stackstorm.slack.com/archives/community/p1474054719001775

**Comment by vishnu81** [comment] 2016-09-16 19:43
there should be second option to use the server time too.
People who have servers in different zones, need to follow three timezones.
Pretty troublesome...

**Comment by enykeev** [comment] 2016-11-24 07:56
I'm going to close the issue for now. The problem stated in the title does not exist. Selecting a custom TZ is better handled as a part of https://github.com/StackStorm/st2web/issues/292.

**Closed by enykeev** 2016-11-24 07:56 UTC
