### ISSUE TITLE
Pack app "Preview" does nothing

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2web#415] opened 2017-08-26 15:03 UTC
Not even clear how it is intended to work, but as of now, just doesn't do anything. 
`st2 v 2.4.0`

![image](https://user-images.githubusercontent.com/1294734/29742480-e426e6a2-8a34-11e7-8ac8-95abceb58362.png)

**Comment by bigmstone** [comment] 2017-08-29 21:10
@dzimine I can't reproduce this issue (Chrome + macOS) - though I'll admit if you don't know to scroll down it appears as though nothing happened. Can you confirm this isn't working or that you did not scroll down?

If it's in fact not working which browser/os combo are you using?

**Comment by rakhesha** [comment] 2017-12-19 13:10
Hi, I too facing the similar issue (StockStorm Version: st2 2.5.0 + Windows 8.1 + Chrome), Is there any particular cause for this issue? Unable explore the "Preview" button. Suggestions are welcome.

**Comment by christopherjbaker** [comment] 2017-12-21 23:24
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6.

**Closed** 2018-01-11 17:28 UTC
Labels: bug, fixed in branch
