### ISSUE TITLE
Feature request: parameters order the same way they are defined in meta

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2web#274] opened 2016-01-14 20:21 UTC
Hello,

It would be nice to order parameters in the WebUI the same way they are defined in meta files. Perhaps, adding an optional `order` field to the parameters in the meta would let it implement easier.

Thanks!

**Comment by armab** [comment] 2016-01-14 20:25
Duplicate of https://github.com/StackStorm/st2web/issues/154

**Comment by Kami** [comment] 2016-01-17 11:02
Closing because it's a duplicate.

Let's please continue in #154 - thanks!

**Closed by Kami** 2016-01-17 11:02 UTC
