### ISSUE TITLE
Default port should not be 9100 if the url property is set

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2web#340] opened 2016-12-16 14:43 UTC
```
'use strict';
angular.module('main')
  .constant('st2Config', {

    hosts: [{
      name: 'StackStorm',
      url: 'http://stackstorm.example.com/api',
      auth: 'http://stackstorm.example.com/auth',
    }]
  });
```

At the moment the code about will request http://stackstorm.example.com:9100/auth. I think that's unexpected behaviour. It's fine to use port 9100 if no url property is set.

It's required to add :80 at the moment to get the above to work:

```
'use strict';
angular.module('main')
  .constant('st2Config', {

    hosts: [{
      name: 'StackStorm',
      url: 'http://stackstorm.example.com:80/api',
      auth: 'http://stackstorm.example.com:80/auth',
    }]
  });
```

**Comment by bigmstone** [comment] 2017-06-20 21:50
I cannot reproduce this and all of the code I've reviewed today shows us using port `80` if the url begins with `http` and `443` if it begins with `https`.

There's no reference to `9100` (for instance) in either the StackStrom/st2web or StackStorm/st2client.js repo.

Perhaps this was fixed at some point, but I will close this issue for now. If you have better steps to reproduce I can try again.

**Closed by bigmstone** 2017-06-20 21:50 UTC
