### ISSUE TITLE
UI is sometimes broken because of Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2web#350] opened 2017-02-21 14:03 UTC
If I click the run button to execute an action in the st2web UI it works just fine. But when I'm browsing in some other browser tabs or develop some code and return back after a while to the still open page, clicking on that same "Run" button doesn't do anything. I see the following error in my browser:

EventSource cannot load https://stackstorm-api.example.org/api/v1/stream?x-auth-token=7ccc6d22fade4e8dbc131b1bz3e91a6b. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://stackstorm.example.org' is therefore not allowed access. /#/history/58ac3ef71bda1c39695z8984/code:1

When I reload the page, everything works fine again.

**Comment by bigmstone** [comment] 2017-06-13 18:39
Do you know about how much time goes by between runs? Trying to reproduce.

**Comment by pietervogelaar** [comment] 2017-06-13 18:47
About 3-15 minutes

**Comment by bigmstone** [comment] 2017-06-13 19:28
Is there anything unique about your setup? I can't reproduce it in that time frame for sure. (Waited 30 minutes just now)

**Comment by pietervogelaar** [comment] 2017-06-13 19:34
I haven't noticed the bug for a while. We are on version 2.2.1, so maybe it's fixed sometime.

**Comment by bigmstone** [comment] 2017-06-14 16:39
@pietervogelaar okay. I will close this issue. Please re-open if you see it again and have some way to reproduce.

**Closed by bigmstone** 2017-06-14 16:39 UTC
