### ISSUE TITLE
Filter by actions doesn't show actions in workflow

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2web#313] opened 2016-06-30 14:51 UTC
We're auto-generating StackStorm rules/actions/etc from our existing crontabs. These auto-generated files wrap a workflow around each cron job that attempts to acquire a lease from Zookeeper before executing an action. This way, multiple StackStorm nodes can trigger a cron job simultaneously and the first to acquire the lease "wins" the right to execute the action; the others fail silently (core.noop).

All of this background is to say that most of our actions are wrapped in workflows now. So we'd expect to be able to search for the core action; however, the action doesn't appear if it executes as part of a workflow.

Here's 2000 words...

Searching by rule shows the workflow with the action:
![](https://s31.postimg.org/xbq2ult7v/Screen_Shot_2016_06_30_at_9_40_39_AM.png)

But searching but action makes it look like it never ran:
![](https://s31.postimg.org/rm58wjxnv/Screen_Shot_2016_06_30_at_9_41_01_AM.png)

Which obviously looks scary (even if its fine) since many of these jobs are critical to our infrastructure.

**Comment by enykeev** [comment] 2016-07-01 03:51
Thanks for the report!

First of all, this is an intended behavior and not a bug. Filters in st2web are only apply to parent executions. This is mostly related to UX and expectations: in general, child executions don't mean much without their parent to give context on what's going on; parent executions are almost never of the same action as the child executions; when you filtering a list of executions by specific action and instead given a list about 50% of which is a seemingly random actions you didn't ask for, you may end up not particularly happy either. There is also some technical hurdles API side to get parent executions for all filtered executions to build proper trees (and still keep response relatively compact so it would not require user wait excessive amount of time). This was our initial reasoning and we decided to give it another go as soon as we get a request from user.

Looking at this particular situation, I can't help but feel that child execution filters would solve the wrong problem. It seems to be that the reason you need this filters is to be able to distinguish between executions that yielded positive results (acquired the lease and executed the action) and those that did not. You would get the means to do that if you would allow latter one to fail and then start filtering by parent workflow name and execution status. The trade off in this case would be the ability to easily spot executions that failed by some other reason (which may or may not be acceptable to you).

We're still trying to find a way how to make this filters more flexible without introducing some complex query language or putting a bunch of bells and whistles to fine tune the results. If you have more cases where advanced filters might be beneficial, please share them with us, it's getting harder and harder to properly reason about this decisions based only on a personal experience.

**Comment by enykeev** [comment] 2016-11-24 08:30
Going to close the issue as there's nothing actionable we can do at the moment. We're still trying to find a good way to make filters more flexible, but are hesitant of adding additional external dependencies for that purpose.

**Closed by enykeev** 2016-11-24 08:30 UTC
Labels: enhancement

**Comment by codyaray** [comment] 2016-11-24 20:04
One of the things that I may try adding support for soon is multiple
filters. For example, showing all failed and timed out executions.

-Cody
