### ISSUE TITLE
Cross-browser IE/FF compatibility issues

### ISSUE THREAD

**Issue by armab** [StackStorm/st2web#151] opened 2015-05-06 19:53 UTC
Nice interfaces!
I know that everything looks just flawlessly in Chrome,
but here are several IE/FF cross-browser compatibility issues I've found that could be useful to know about: 

##### IE11: 
![ie-login](https://cloud.githubusercontent.com/assets/1533818/7501996/5318682e-f441-11e4-8efd-abd4253d20ae.gif)

##### Firefox: 
![ff-login](https://cloud.githubusercontent.com/assets/1533818/7502086/1557f1b6-f442-11e4-8d64-7a8526b90fd1.gif)

##### IE11:
![ie-scrolling](https://cloud.githubusercontent.com/assets/1533818/7502028/9c551fd2-f441-11e4-8b3c-462b1d000c7c.gif)

##### Firefox:
![ff-scrolling](https://cloud.githubusercontent.com/assets/1533818/7502036/a8fb35b4-f441-11e4-97df-baf6d7e46dcf.gif)

##### No autocomplete for "Action name" in IE11:
![ie-autocomplete](https://cloud.githubusercontent.com/assets/1533818/7501974/10f1172a-f441-11e4-952a-ccabc167f6db.gif)

Thanks!

**Comment by enykeev** [comment] 2015-05-07 15:12
Thanks for report!

I have to admit, we haven't tested it for IE at all and I'm not sure if we're going to do it anytime soon.

As for Firefox, seems like core team is not going to implement scroll customization on their side (https://bugzilla.mozilla.org/show_bug.cgi?id=77790, 14 years!) and the only way for us to deal with the problem is to recreate scrolling behavior in JS. We have this task in backlog, but as with IE, this is not a priority at the moment. Interestingly enough, Firefox on OSX with retina has another type of scrolls that look very much as the one we're using. May be by the time we get to that, it would become default style in every version.

The fact that `select` doesn't hide the button in windows version of Firefox (works in OSX) is interesting and requires additional investigation.

**Comment by emedvedev** [comment] 2015-12-18 01:07
This one is partly resolved by @alex-shnayder (custom scrolls mostly work in Firefox with a polyfill afaik—at least where they can), dropdowns also aren't a problem in the most recent version. Closing.

**Closed by emedvedev** 2015-12-18 01:07 UTC
