### ISSUE TITLE
Text in select boxes are not visible until mouseover

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2web#355] opened 2017-05-11 14:09 UTC
On Windows, text in select boxes are not visible until mouseover.  This is both on Firefox and Chrome. In Internet Explorer only a white page is visible. Is Internet Explorer not supported at all for st2web?

On Mac everything works great with Chrome and Firefox.

**Comment by estee-tew** [comment] 2017-05-15 20:13
https://stackstorm.slack.com/archives/community/p1494879221234565

**Comment by LindsayHill** [comment] 2017-05-15 20:17
Confirmed: OS-specific. Fails when Windows 10 used, works with macOS.

**Comment by LindsayHill** [comment] 2017-05-15 20:17
Also, seems to have been problem since at least st2 2.1.1 (my test was with BWC 2.1.1 system)

**Comment by nzlosh** [comment] 2017-05-15 20:28
I have the same issue under Linux with FF 45.9.0 ESR http://imgur.com/a/4wxfo
Looking at the style information, this where it's getting set to white
```
.st2-auto-form__field option {
    color: white;
}
```
If I set `color` to black the drop down box shows all entries.

**Comment by LindsayHill** [comment] 2017-06-13 18:26
Fixed by #356

**Closed by LindsayHill** 2017-06-13 18:26 UTC

**Comment by bigmstone** [comment] 2017-06-13 18:40
@pietervogelaar @nzlosh This was fixed in #356. Let us know if this does not resolve the issue.
