### ISSUE TITLE
Add reinstall pack from pack view

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#435] opened 2017-11-28 10:28 UTC
ER(usability): This will be better UI than having to go to history, filter by actions: packs.install, waiting for GUI update, choosing the right one then using re-run...

**Comment by LindsayHill** [comment] 2017-11-28 17:46
Q: Under what circumstances would a user want to re-install a pack?

The existing packs tab will let you install updates if a new version is available, but it doesn't currently let you reinstall if there's no change in version. Is there a reason you're re-installing the same version?

**Comment by vincent-legoll** [comment] 2017-11-28 18:21
OK I've never seen the update pack button because I never change the version of my in-development pack, and just re-run from the last packs.install execution.

I'll try in the next days and will update this ER (or close)

**Comment by vincent-legoll** [comment] 2017-12-01 16:25
OK I've never seen the update pack button because I never change the version of my in-development pack, and just re-run from the last packs.install execution.

I'll try in the next days and will update this ER (or close)

**Comment by vincent-legoll** [comment] 2017-12-01 16:27
OK I'm not seing the update pack button after having pushed a pack version update, maybe this is because my github repo is private...

**Comment by LindsayHill** [comment] 2017-12-01 17:05
Ah, there's a couple of things going on here.

One is that I was incorrect in what I said earlier. The Packs UI will highlight if a new pack is available, but it does not give you a reinstall/upgrade button.  See https://stackstorm.com/wp/wp-content/uploads/2017/08/pack_versions.png - note the color highlighting for the Jira & Sensu packs.

Clearly that would be a useful enhancement, to provide an "upgrade" button if a new version is detected.

Secondly, versions are checked by querying the index metadata. ST2 is not checking the original location for every pack. By default it queries index.stackstorm.org, but can also query internal indexes. See https://docs.stackstorm.com/packs.html#hosting-your-own-pack-index. In your case, if you don't have your pack indexed, then the Web UI is never going to be able to detect new versions. 

So maybe it does make sense to have a re-install command...except...if you're installing from a custom location, then how will that reinstall button know what source to install the pack from? It's just going to do `st2 pack install <mypack>`, which is going to query the index.

**Comment by vincent-legoll** [comment] 2017-12-01 18:54
Yeah, the update from index will not work for my use case, but would be a nice enhancement anyways.

But in addition to that, a "Reinstall" button (doing a re-run of last known packs.install action for that pack) would be nice too...

**Comment by LindsayHill** [comment] 2017-12-01 18:58
> doing a re-run of last known packs.install action for that pack

The problem is that there's more than one way to load a pack, and it doesn't always use `packs.install`, and that info is not stored in the pack, so I don't know how we can make that reliably work.

**Comment by christopherjbaker** [comment] 2018-01-11 20:15
Closing due to the ambiguity of parameters, inability to retrieve previous, and low use case.

**Closed by christopherjbaker** 2018-01-11 20:15 UTC
Labels: wontfix
